### PR TITLE
[LINUX BUILD] Mono port: support 64-bit builds, incl. non-apt distros

### PR DESCRIPTION
**Pull request by matoro**
Surprisingly this worked without a hitch - the only problem is the configuration menu crashes (don't know if this is because of missing the bundled mono and using system instead?)  However the actual plugin functionality works with no config needed.  It detects architecture from the install PCSX2 binary.

### CODE REVIEW

**Comment by TheLastRar** [comment]
Thank you

**Comment by Hunk4TH** [comment]
Is there a version already compiled to work with the latest PCSX2 x64 builds in Linux?

**Comment by matoro** [comment]
> Is there a version already compiled to work with the latest PCSX2 x64 builds in Linux?

This is the build I made when creating this pull request.  I was able to play through all of RE Outbreak using it no problem.  I have only tested this against the 1.7.0 development branch, not against stable, so can't vouch for it on the latter.  As stated, the configuration menu does not work.

[libclrdev9mono.Release.tar.gz](https://github.com/TheLastRar/CLR-DEV9/files/5580835/libclrdev9mono.Release.tar.gz)

**Comment by Hunk4TH** [comment]
> > Is there a version already compiled to work with the latest PCSX2 x64 builds in Linux?
> 
> This is the build I made when creating this pull request. I was able to play through all of RE Outbreak using it no problem. I have only tested this against the 1.7.0 development branch, not against stable, so can't vouch for it on the latter. As stated, the configuration menu does not work.
> 
> [libclrdev9mono.Release.tar.gz](https://github.com/TheLastRar/CLR-DEV9/files/5580835/libclrdev9mono.Release.tar.gz)

Amazing thank you! So I put it in the plugins directory, do I have to select it anywhere? I noticed that the latest builds include the original Dev9 plugin by default. You used to be able to select which Dev9 plugin to use.

**Comment by TheLastRar** [comment]
See https://github.com/TheLastRar/CLR-DEV9/issues/31

The 1.7.0 PCSX2 builds have been slowly integrating it's plugins (removing the ability to select 3rd party ones)
I am helping with bringing over some of the features of CLR-DEV9 into PCSX2 (mainly HDD support, winsock is currently being excluded)

This is one of the reasons I've been hesitant to provide x64 Linux builds (as x64 support was added post 1.6.0)

**Comment by Hunk4TH** [comment]
> See #31
> 
> The 1.7.0 PCSX2 builds have been slowly integrating it's plugins (removing the ability to select 3rd party ones)
> I am helping with bringing over some of the features of CLR-DEV9 into PCSX2 (mainly HDD support, winsock is currently being excluded)
> 
> This is one of the reasons I've been hesitant to provide x64 Linux builds (as x64 support was added post 1.6.0)

Yeah, I've noticed that. Shame they took away being able to select a different Dev9 plugin. I know CLR-DEV9 winsock is definitely better at least in my experience than the default one. I used to freeze randomly a lot using the default plugin in Windows 10. But never with the winsock one. 

The one you compiled above does it somehow replace the default one meaning we're running the winsock version instead of the default? If that makes sense?

**Comment by matoro** [comment]
> > See #31
> > The 1.7.0 PCSX2 builds have been slowly integrating it's plugins (removing the ability to select 3rd party ones)
> > I am helping with bringing over some of the features of CLR-DEV9 into PCSX2 (mainly HDD support, winsock is currently being excluded)
> > This is one of the reasons I've been hesitant to provide x64 Linux builds (as x64 support was added post 1.6.0)
> 
> Yeah, I've noticed that. Shame they took away being able to select a different Dev9 plugin. I know CLR-DEV9 winsock is definitely better at least in my experience than the default one. I used to freeze randomly a lot using the default plugin in Windows 10. But never with the winsock one.
> 
> The one you compiled above does it somehow replace the default one meaning we're running the winsock version instead of the default? If that makes sense?

Damn, I didn't even notice that.  I played it a couple months back and they must have removed the ability to select DEV9 plugins.  I am not sure actually how to change it now, I would have to look into it.  Sorry mate.

**Comment by Hunk4TH** [comment]
> > > See #31
> > > The 1.7.0 PCSX2 builds have been slowly integrating it's plugins (removing the ability to select 3rd party ones)
> > > I am helping with bringing over some of the features of CLR-DEV9 into PCSX2 (mainly HDD support, winsock is currently being excluded)
> > > This is one of the reasons I've been hesitant to provide x64 Linux builds (as x64 support was added post 1.6.0)
> > 
> > 
> > Yeah, I've noticed that. Shame they took away being able to select a different Dev9 plugin. I know CLR-DEV9 winsock is definitely better at least in my experience than the default one. I used to freeze randomly a lot using the default plugin in Windows 10. But never with the winsock one.
> > The one you compiled above does it somehow replace the default one meaning we're running the winsock version instead of the default? If that makes sense?
> 
> Damn, I didn't even notice that. I played it a couple months back and they must have removed the ability to select DEV9 plugins. I am not sure actually how to change it now, I would have to look into it. Sorry mate.

Yeah, I know I froze a lot randomly using that plugin. It's cool man not your fault. Not sure why they decided to remove that ability for.

**Comment by TheLastRar** [comment]
If you are getting freezing issues in 1.7.0 with the its internal DEV9, please open a new issue with as much detail as you can provide

**Comment by Hunk4TH** [comment]
> If you are getting freezing issues in 1.7.0 with the its internal DEV9, please open a new issue with as much detail as you can provide

No sorry. I was referring to the DEV9 plugin that comes bundled with PCSX2 in the past pre 1.6. Trying to figured out how to get your plugin working with the latest builds but I don't think it's possible :/

**Comment by TheLastRar** [comment]
The fixes for the freezing issues was added sometime in during 1.5.0 development (by me), so 1.6.0 _should_ be as stable as CLR_DEV9 in that regard.

I was referring to the bundled plugin when I asked, in-case I failed to port over any freezing fixes in CLR_DEV9.

**Comment by Hunk4TH** [comment]
> The fixes for the freezing issues was added sometime in during 1.5.0 development (by me), so 1.6.0 _should_ be as stable as CLR_DEV9 in that regard.
> 
> I was referring to the bundled plugin when I asked, in-case I failed to port over any freezing fixes in CLR_DEV9.

Oh my bad I guess I misunderstood. So in the latest 1.7 builds the bundled plugin should be as stable?

**Comment by TheLastRar** [comment]
That is what I'm hoping

**Pull request merged**
